# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: baioc
title_separator: "|"
masthead_title: "About"
# logo: "/assets/images/avatar-88x88.png"
email: baiocchi.gabriel@gmail.com
github_username: baioc
minimal_mistakes_skin: "contrast" # "mint", "contrast", "dark", "neon"
search: true
search_full_content: true

# This fixes "GitHub Metadata" errors
# found at https://github.com/github/pages-gem/issues/399 and also
# https://github.com/jekyll/github-metadata/blob/master/docs/configuration.md#configuration
github: [metadata]
repository: baioc/baioc.github.io

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 3 # amount of posts to show
teaser: /assets/images/wizard.png
paginate_path: /blog/page:num/
locale: "en"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

author:
  name: "Gabriel Baiocchi de Sant'Anna"
  avatar: "/assets/images/photo.jpg"
  bio:  >- # this means ignore new lines
    Computer Science student and former research assistant at the Embedded Computing Laboratory (ECL UFSC) Video Coding team, with a background in Electronics.
  # location: "Brazil / France"
  links: # look for icons at https://fontawesome.com/icons/
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/baioc"
    - label: "GitLab"
      icon: "fab fa-gitlab"
      url: "https://gitlab.com/baioc"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/baioc/"
    - label: "Lattes"
      icon: "fas fa-eye"
      url: "http://lattes.cnpq.br/5048826722066095"

# enables MathJax, as explained at https://alan97.github.io/random/mathjax/
# with reference to documentation at https://mmistakes.github.io/minimal-mistakes/docs/javascript/
head_scripts:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML

footer:
  # links:
  #   - label: "Twitter"
  #     icon: "fab fa-fw fa-twitter-square"
  #     url: "https://twitter.com/gbaiocs"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: false
      comments: true
      share: false
      related: true
      author_profile: false
      search: true
      toc: true
      toc_icon: "bars"
      toc_label: "Contents"
      toc_sticky: yes
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: archive
      author_profile: true
      search: false
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      search: true
      comments: true
      related: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

comments:
  provider: "disqus"
  disqus:
    shortname: "baioc"

# for more information check out:
# Utilities - https://mmistakes.github.io/minimal-mistakes/docs/utility-classes/
# Helpers - https://mmistakes.github.io/minimal-mistakes/docs/helpers/
# Jekyll - https://jekyllrb.com/docs/
